name: "Run Test Coverage and Upload it to Codecov"

on:
  push:
    branches:
      - master

    paths:
      - ".github/workflows/code-coverage-report.yml"
      - "src/**"

jobs:
  Tests-Upload-Coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Running Tests with Coverage Report"
        run: |
          yarn
          yarn test --coverage
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          name: codecov-l2t
          fail_ci_if_error: true
        env:
          CI: true
